### ISSUE TITLE
TimeLine on the top

### ISSUE THREAD

**Issue by CheburashkaS** [tradingview/lightweight-charts-android#102]
Hi! Is there any way to make time line on the top? Something like this:

![image](https://user-images.githubusercontent.com/4688272/149312143-b70ed11d-c813-43a4-bec2-ff5958ba5956.png)

Or can you provide this like a new feature?

**Comment by timocov** [comment]
Currently it is impossible, please create a feature request in https://github.com/tradingview/lightweight-charts for this.
