### ISSUE TITLE
Animating Movement Data on Chart

### ISSUE THREAD

**Issue by iman051996** [tradingview/lightweight-charts-android#108]
Want to know, 
how to make movement data on chart is animated, 
ex : 
while data is goin up, bar data goin animated up, otherwise down

is it possible to make animated like that ?

**Comment by timocov** [comment]
There is no option for that and I'm afraid we have no plans to add this in the future.

**Comment by timocov** [comment]
#1008

**Comment by iman051996** [comment]
how to get that feature? is it have another plan for lib tradingview on android?
if it require to pay, we will pay it

**Comment by timocov** [comment]
> how to get that feature? is it have another plan for lib tradingview on android?

from https://github.com/tradingview/lightweight-charts-android/issues/108#issuecomment-1044740383:

> I'm afraid we have no plans to add this in the future.
