### ISSUE TITLE
subscribeClick is not working 

### ISSUE THREAD

**Issue by VishwasNagarkar** [tradingview/lightweight-charts-android#117]
Hi Team,

 subscribeClick method is not working in v3.8.0 in previous versions its working fine, please let me know if there is an implementation change. if it is then please provide a sample code of it 

Thanks 
Vishwas Nagarkar

**Comment by makedonsky94** [comment]
Hi! Thanks for the ticket. At the time we investigating the issue. I'll come back with more information little bit later.

**Comment by makedonsky94** [comment]
Currently `subscribeClick` is not working in touch mode

**Comment by romfrancois** [comment]
Hi @VishwasNagarkar !
A fix has been provided for this issue. Feel free to try your scenario again and come back to us if there’s anything wrong.
