### ISSUE TITLE
Default browser style

### ISSUE THREAD

**Issue by serdimoa** [tradingview/lightweight-charts-android#13]
Hello, has issue in sizing of chart because browser has default margin 
![image](https://user-images.githubusercontent.com/1455192/96101228-eb1c6500-0edd-11eb-9fc3-27adb01f6aa1.png)

Proposal: Reset default browser style for body

**Comment by makedonsky94** [comment]
Hey! We will remove that margin on the next update

**Comment by makedonsky94** [comment]
The new version is available and contains the fix
