### ISSUE TITLE
A lot of logs

### ISSUE THREAD

**Issue by serdimoa** [tradingview/lightweight-charts-android#14]
When I use charts with subscribe to visible range and use real time update from ws or rest has a lot of logs
![image](https://user-images.githubusercontent.com/1455192/96453766-9e10f980-1223-11eb-83d1-5f23908607a6.png)
Proposal: Need option for disable logs

**Comment by makedonsky94** [comment]
We will provide the option in the next update

**Comment by makedonsky94** [comment]
The library will write warnings and errors to the logcat by default. You can change it by overriding logLevel in ChartsView
```
class NoLogsChartsView(context: Context, attrs: AttributeSet? = null) : ChartsView(context, attrs) {
    override val logLevel: LogLevel
        get() = LogLevel.NONE
}
```
