### ISSUE TITLE
Bug does not restore the state view

### ISSUE THREAD

**Issue by eugenSt20** [tradingview/lightweight-charts-android#19]
We used viewPager.
Add ChartsView to our fragment.
Add tabLayout.
After click tab we go next page.
After click tab where we added ChartsView.
Result: not correct view ChartsView

You clearWebMessageChannel from onDetachedFromWindow but not use  webMessageController.setWebMessageChannel(channel) for onAttachedToWindow

Can you help?

**Comment by makedonsky94** [comment]
Hi!
At onAttachedToWindow we call super.loadUrl(DEFAULT_URL). That means we reload the page if charts view was detached and attached again. I will investigate this case and try to implement restoring state

**Comment by eugenSt20** [comment]
> Hi!
> At onAttachedToWindow we call super.loadUrl(DEFAULT_URL). That means we reload the page if charts view was detached and attached again. I will investigate this case and try to implement restoring state

Thanks

**Comment by EvgenBES** [comment]
I have this problem too

**Comment by EvgenBES** [comment]
there is a solution?

**Comment by makedonsky94** [comment]
There is no solution yet. Saving state is complicated thing. Right now you can save the state by yourself and pass it after the view has been attached.
We will implement the solution in the next iteration.

**Comment by EvgenBES** [comment]
OK.
It means you managed to reproduce this problem.
We are waiting for a decision;)

**Comment by makedonsky94** [comment]
After the investigation I found that there is no way to save the display state of WebView. So there is no way to save state of the ChartsView when fragment is destroying view. I made the fix so you can use ViewPager2. Also the example of ViewPager2 usage is here. Pls look at the pull request
