### ISSUE TITLE
Gradle error

### ISSUE THREAD

**Issue by ugar0ff** [tradingview/lightweight-charts-android#2]
When I add dependencies at gradle, I have error:
_Failed to resolve: com.tradingview:lightweightcharts:1.0.0-beta_

**Comment by makedonsky94** [comment]
Hi!
Did you declare the maven repository in project build.gradle file?

```groovy
allprojects {
    repositories {
        ...
        maven {
            url "https://dl.bintray.com/tradingview-org/charts"
        }
    }
}
```

**Comment by ugar0ff** [comment]
Yes i did it
![Снимок экрана (77)](https://user-images.githubusercontent.com/14922730/89507016-9de09080-d7d4-11ea-9dea-0e2297fcf818.png)
![Снимок экрана (78)](https://user-images.githubusercontent.com/14922730/89507027-a0db8100-d7d4-11ea-846b-1a0cd3273019.png)
