### ISSUE TITLE
How to Format the date on X axis ?

### ISSUE THREAD

**Issue by supriyakhankarnw18** [tradingview/lightweight-charts-android#20]
fun chartOptions(width: Int, height: Int): ChartOptions {
    return ChartOptions(
        width = width,
        height = height,
        timeScale = timeScaleOptions(),
        localization = LocalizationOptions(
            locale = "de-AT",
            priceFormatter = "function (price) { return price + 'k'; }",
            timeFormatter = "function (time) { return time + 'k'; }",
            dateFormat = DateFormat.FORMAT_2
        )
    )
}

I'm trying to format the date on X-axis By using the above code. But it is showing the same date for all the DateFormat

**Comment by makedonsky94** [comment]
Do you want to customize the time scale? Unfortunately it's not supported by now. 
The current version of android library is based on Lightweight chart v2. 
Customization of time scale included in [Lightweight charts v3](https://github.com/tradingview/lightweight-charts/releases/tag/v3.0.0). We will use this version in the next update.

**Comment by supriyakhankarnw18** [comment]
what is the expected date of the next realize with Lightweight charts v3. ?

**Comment by makedonsky94** [comment]
Currently we focused on implementing all new features presented in v3
I think we can release the new version till the end of the year

**Comment by makedonsky94** [comment]
The new version is available. You can set your own formatter for time scale.
```
chartApi.applyOptions {
    timeScale = timeScaleOptions {
        tickMarkFormatter = TickMarkFormatter()
    }
}
```
`TickMarkFormatter` - custom plugin. You can check its implementation in the chart demo
