### ISSUE TITLE
Not Able to Format Date in different format in the latest version 

### ISSUE THREAD

**Issue by supriyakhankarnw18** [tradingview/lightweight-charts-android#27]
I have tried to format the date in the latest version no. 3.2.0-rc1
 Not possible to change the time format from (1611122880) epoch on the x-Axis
Example for 1 day -- 9:30 AM, 11:05 AM ...
for 1 week -- 19 Jan, 18 Jan, 15 Jan ...
for 1 Month -- Jan20, Dec19 , Nov19 , ...
for 1 year -- Feb2020 , May2020 , Jul2020 ...
for 5 year -- 2020, 2019, 2018 ....

Kindly Suggest

**Comment by makedonsky94** [comment]
Hi! You should set `tickMarkFormatter` for the chart.

The parameter [tickMarkFormatter](https://github.com/tradingview/lightweight-charts-android/blob/master/lightweightlibrary/src/main/java/com/tradingview/lightweightcharts/api/options/models/TimeScaleOptions.kt#L22) is defined as plugin. So you should pass the object inherited from Plugin class. The most easiest way is to use [Eval](https://github.com/tradingview/lightweight-charts-android/blob/master/lightweightlibrary/src/main/java/com/tradingview/lightweightcharts/runtime/plugins/Eval.kt) class. 

It could be something like that:
```kotlin
chartApi.applyOptions {
    timeScale = timeScaleOptions {
        tickMarkFormatter = Eval("""
            function(time, tickMarkType, locale) {
                let timeMillis = time * 1000;
                let nowMillis = Date.now();
                let diff = nowMillis - timeMillis;
                
                console.log("timeMillis:", timeMillis);
                console.log("nowMillis:", nowMillis);
                console.log("diff:", diff);
                
                if (diff < 86400000) {
                    //format timestamp
                    return "9:30 AM";
                }
                
                if (diff < 86400000 * 7) {
                    //format timestamp
                    return "19 Jan";
                }
                
                if (diff < 86400000 * 30) {
                    //format timestamp
                    return "Jan20";
                }

                //format timestamp
                return "Feb2020";
            }
        """.trimIndent())
    }
}
```

![image](https://user-images.githubusercontent.com/11327827/105173711-75561400-5b32-11eb-9282-72c00855eb2c.png)
