### ISSUE TITLE
Facing issue for removing current series from chart

### ISSUE THREAD

**Issue by supriyakhankarnw18** [tradingview/lightweight-charts-android#28]
I'm using the below code for removing the current series from the sample app

leftSeries.forEach(firstChartApi::removeSeries)
leftSeries.clear()

getting below error
Type inference failed: inline fun <T> Iterable<T>.forEach(action: (T) -> Unit): Unit
cannot be applied to
receiver: MutableList<SeriesApi>  arguments: (KFunction2<@ParameterName SeriesApi, @ParameterName(name = "onSeriesDeleted") () -> Unit, Unit>)

Please suggest

**Comment by makedonsky94** [comment]
Hi! Can you check the version of kotlin plugin for IDE?

Also please check the version of kotlin version using in the project.

I guess that might be the problem with method signature with default params. https://youtrack.jetbrains.com/issue/KT-8834

**Comment by supriyakhankarnw18** [comment]
hi team our current version is this ext.kotlin_version = '1.3.60'
due to some limitations, we are not able to update the kotlin version frequently 
could you please provide the support for the clear functionally on the kotlin version(ext.kotlin_version = '1.3.60')

**Comment by makedonsky94** [comment]
```kotlin
leftSeries.forEach(firstChartApi::removeSeries)
leftSeries.clear()
```
In this statement you can see the method reference `firstChartApi::removeSeries`. That statement only possible in kotlin v1.4.
As I said this caused by limitation of method signature created by kotlin compiler.
If you want to avoid the compilation error you should use lambdas instead of method reference.
```kotlin
leftSeries.forEach {
    firstChartApi.removeSeries(it)
}
leftSeries.clear()
```
