### ISSUE TITLE
fitContent() not working first time 

### ISSUE THREAD

**Issue by supriyakhankarnw18** [tradingview/lightweight-charts-android#29]
Im trying to use "firstChartApi.timeScale.fitContent()" in the sample app after setting the data but it is not working on 1st time on 2nd time it working properly could you please provide a sample on how to use it with a dynamic chart 

My sample code:-

 private fun createSeriesWithData(
        data: Data,
        priceScale: PriceScaleId,
        chartApi: ChartApi,
        onSeriesCreated: (SeriesApi) -> Unit) {
        when (data.type) {
            SeriesDataType.LINE -> chartApi.addLineSeries(
                options = LineSeriesOptions(
                    priceScaleId = priceScale
                ),
                onSeriesCreated = { api ->
                    api.setData(data.list)
                    onSeriesCreated(api)
                }
            )

            SeriesDataType.CANDLESTICK -> {
                chartApi.addCandlestickSeries(
                        options = CandlestickSeriesOptions(
                                priceScaleId = priceScale
                        ),
                        onSeriesCreated = { api ->
                            api.setData(data.list)
                            onSeriesCreated(api)
                        }
                )
                chartApi.timeScale.fitContent()
            }
            
        }
        firstChartApi.timeScale.fitContent()
    }

**Comment by makedonsky94** [comment]
Hi! Creating of series is async operation. So you should put the method `fitContent` right after the setting of data.

like this

```kotlin
        SeriesDataType.CANDLESTICK -> {
            chartApi.addCandlestickSeries(
                    options = CandlestickSeriesOptions(
                            priceScaleId = priceScale
                    ),
                    onSeriesCreated = { api ->
                        api.setData(data.list)
                        //Resize time scale
                        chartApi.timeScale.fitContent()
                        onSeriesCreated(api)
                    }
            )
        }
```

**Comment by Bikeskin** [comment]
Hi @makedonsky94,
I dont want to create a new issue.
I used charts on two screens of my app and fitContent works very rearly, i faced this problem both of them. 
First one is dashboard screen; first load ss, refresh ss and codes;
![dashboard_first](https://user-images.githubusercontent.com/17744411/186884610-3233afbd-1e05-4d39-baa4-052d627420e2.png)  ![dashboard_refresh](https://user-images.githubusercontent.com/17744411/186884650-2c7c5187-35d8-4dde-b7ee-a2703618dd6e.png)

        viewModel.lineData.observe(viewLifecycleOwner) { data ->
            if (::areaSeries.isInitialized) {
                binding.tradingView.api.removeSeries(areaSeries)
            }
            binding.tradingView.api.addAreaSeries(
                options = addOptions(
                    requireContext(),
                    viewModel.chartColor
                ),
                onSeriesCreated = { api ->
                    areaSeries = api
                    areaSeries.setData(data.list)
                    if (data.list.size > 20) {
                        binding.tradingView.api.timeScale.fitContent()
                    }
                    viewModel.hideChartLoading()
                }
            )
        }

Second one is detail screen: first load ss, refresh ss and codes;

![detail_first](https://user-images.githubusercontent.com/17744411/186885895-601ef419-606d-434b-8fcd-cb2597c2f6bb.png) ![detail_refresh](https://user-images.githubusercontent.com/17744411/186885909-731313a8-6c18-4b49-a0f2-cd64fff1185f.png)

    private fun createSeriesWithData(
        data: Data,
        chartApi: ChartApi,
        onSeriesCreated: (SeriesApi) -> Unit
    ) {
        chartApi.addAreaSeries(
            options = addOptions(requireContext(), colorId),
            onSeriesCreated = { api ->
                api.setData(data.list)
                binding.tradingView.api.timeScale.fitContent()
                onSeriesCreated(api)
            }
        )
    }
