### ISSUE TITLE
 seriesName is not defined

### ISSUE THREAD

**Issue by supriyakhankarnw18** [tradingview/lightweight-charts-android#40]
Hi Team, 
we are showing the Area and candle chart with the click of the switch button. if we Switch fast between these 2 chart we get this error  on the below code lines

1) firstChartApi!!.removeSeries(it)

Process: com.divum.MoneyControl.debug, PID: 5168
    java.lang.IllegalStateException: seriesName is not defined
        at com.tradingview.lightweightcharts.runtime.controller.WebMessageController.onMessage(WebMessageController.kt:124)
        at com.tradingview.lightweightcharts.runtime.WebMessageChannel$1.onMessage(WebMessageChannel.kt:26)

**Comment by makedonsky94** [comment]
Hi! Can you provide a demo for further investigation? Seems like there is a bug in management of message queue

**Comment by supriyakhankarnw18** [comment]
Sorry it will take time to create the same replica of the demo with the issue

but we get the same crash on this below line also 

 currentSeriesApiFirstChart.lastOrNull()?.update(event.data as SeriesData)

**Comment by makedonsky94** [comment]
Unfortunately, I can't say what happening in your code without the demo. Check you don't call removeSeries multiple times for the same series. Also, any calls to removed series will lead to crash. You should handle that case by yourself

It could be caused by recreation of view. For example, if you switching fragments by replace but saving links to series anywhere else (singletone or static fields). I think we can make some checks for that case

**Comment by supriyakhankarnw18** [comment]
I have added all the possible conditions at my end. But still, sometimes crashes happen. it will be better if you provide some checks for that case

**Comment by makedonsky94** [comment]
At the coming major release we will provide better handling of invalidated links to SeriesApi. I hope that would help to debug your issue

**Comment by romfrancois** [comment]
@supriyakhankarnw18 what would be the most likely scenario(s) to raise those errors? Just to be sure that our tests will be covering your use cases in addition to some others.

**Comment by supriyakhankarnw18** [comment]
@romfrancois  after using this line **this.series.forEach(charts_view.api::removeSeries)** mostly its gets crashed onbackpress of fragments transactions and some times randomly also its gets crashed 

you can refer to the below ticket also 
https://github.com/tradingview/lightweight-charts-android/issues/74

**Comment by FajarDw** [comment]
@supriyakhankarnw18 I'm having the same problem. have you got a solution for this issue?
