### ISSUE TITLE
White screen on place of chart view while taking screenshot programmatically

### ISSUE THREAD

**Issue by supriyakhankarnw18** [tradingview/lightweight-charts-android#50]
Hi team,
We are facing white screen issue in place of ChartsView while taking screenshot programmatically.
Also whenever new data is rendered or when we change duration, the white screen is visible for fraction of seconds then chart is loaded(i.e from 1d to 5d > first white screen gets loads then old graph and new graph gets rendered)

**Comment by makedonsky94** [comment]
Hi! Hardware acceleration cause this problem. We do not want to turn it off so we will implement the method from charting library. JS backend able to make screenshots without turning off hardware acceleration.

The other question is related to this issue https://github.com/tradingview/lightweight-charts-android/issues/38

**Comment by supriyakhankarnw18** [comment]
When Hardware acceleration set to false then pragmatically capturing screenshots are working fine, but due to some dependencies we cant go with `android:hardwareAccelerated="false"`
Also as you said "JS backend able to make screenshots without turning off hardware acceleration" it was not in our case.

**Comment by makedonsky94** [comment]
We will implement the screenshot method in the future updates. https://github.com/tradingview/lightweight-charts-android/issues/45

**Comment by makedonsky94** [comment]
Add a new method `takeScreenshot`. You can check the usage of this method in [demo](https://github.com/tradingview/lightweight-charts-android/blob/master/app/src/main/java/com/tradingview/lightweightcharts/example/app/view/charts/BarChartFragment.kt#L112)
