### ISSUE TITLE
java.lang.IllegalStateException: Cannot update oldest data, last time=1626696600, new time=1626696300

### ISSUE THREAD

**Issue by supriyakhankarnw18** [tradingview/lightweight-charts-android#52]
Hi Team,
       The application is getting crashed because of the following error  "java.lang.IllegalStateException: Cannot update oldest data, last time=1626696600, new time=1626696300"

is there any Check or way to avoid the crash

**Comment by timocov** [comment]
> is there any Check or way to avoid the crash

@supriyakhankarnw18 If you want to update not the last bar, you have to use `setData` instead of `update`, since `update` might be used to update the latest bar or to add a new one.

**Comment by supriyakhankarnw18** [comment]
@timocov  we want to update it only. but there might be some cases where we can get such data. we just want that in any case application should not get crashed

**Comment by timocov** [comment]
@supriyakhankarnw18 not quite sure that got your point.

> we just want that in any case application should not get crashed

the application won't crash if you will use the api properly. If you're trying to use `update` not for latest bar it will crash for sure.

**Comment by supriyakhankarnw18** [comment]
@timocov You can do some validation on library's end , so that it won't crash.

**Comment by timocov** [comment]
@supriyakhankarnw18 this is exactly what we do and that's why you get you app crashed. Almost any incorrect usage of the library will cause the crash of the app. Otherwise you will never get the fact of incorrect usage (if the library will be silent).

Please consider use the library in correct way.
