### ISSUE TITLE
Showing white screen on back press of fragment transition

### ISSUE THREAD

**Issue by supriyakhankarnw18** [tradingview/lightweight-charts-android#57]
Hi team, we are facing white screen issue over chart view when replacing a fragment on back press and navigating to the previous chart fragment.

Sharing code snippet which have been used for fragment transaction which is shared in sample app, here we only added backStack line `.addToBackStack("tag")`, also shared a video reference.

`private fun <T : Fragment> startFragment(fragmentClass: Class<T>) {
        supportFragmentManager
                .beginTransaction()
                .replace(
                        R.id.fragment_container_fl,
                        FragmentFactory.getInstance(fragmentClass)
                )
                .addToBackStack("tag")
                .commit()
    }`

https://user-images.githubusercontent.com/70312717/128169430-c07b28c7-4f35-4ef8-bb51-39216bd7e1ca.mp4

**Comment by makedonsky94** [comment]
Hi! This issue relates to https://github.com/tradingview/lightweight-charts-android/issues/38

The canvas of webview drawing white background right after creation. In your case a fragment recreating view after every transaction of fragment manager. This is how fragments work on Android
