### ISSUE TITLE
subscribeCrosshairMove got IllegalStateException

### ISSUE THREAD

**Issue by alextangcryptodotcom** [tradingview/lightweight-charts-android#6]
when i use subscribeCrosshairMove to get the crosshair's data, I got the IllegalStateException as shown in the picture below

![Screenshot 2020-08-27 at 12 10 06 AM](https://user-images.githubusercontent.com/56287405/91328690-d08d1000-e7f9-11ea-9beb-cfc6712a312d.png)

**Comment by makedonsky94** [comment]
Hi! 
I found the problem in serialisation module. 
I will push the fix in the next beta release

**Comment by makedonsky94** [comment]
There is a new beta version of lightweight library with fixes for crosshair mode
https://github.com/tradingview/lightweight-charts-android/releases/tag/v1.0.0-beta02
