### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by shahradelahi** [tradingview/lightweight-charts-android#84]
It's working with SDK Version 28 and higher, but it's not working below that.

```
W/zygote: Attempt to remove non-JNI local reference, dumping thread
I/chromium: [INFO:CONSOLE(3802)] "Uncaught SyntaxError: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('#2962ff4c') could not be parsed as a color.", source: file:///android_asset/com/tradingview/lightweightcharts/scripts/app/main.js (3802)
```

It's just keeps crashing and sometimes showing a black screen.

Screenshot: https://imgur.com/a/u9b5qgx

**Comment by makedonsky94** [comment]
Hi! What version of webview do you have on devices with SDK below 28?

**Comment by shahradelahi** [comment]
Hi, 
I tested out the demo app on 3 different SDK's (26, 27, 28), and here is the result.

Demo app: https://imgur.com/a/rF88QU6
Webview version: https://imgur.com/a/Rbckhsi

I tied to update the Webview, but it's not available!
Google Play: https://imgur.com/a/lfnktnE

Also tried it on my own phone (SDK 28) it was working fine same as emulator SDK 28.

**Comment by makedonsky94** [comment]
It's impossible to fix this in the library. WebView in SDK is a proxy class and its implementation is provided by vendor's firmware. In some devices you can change implementation of WebView in developer settings. 

Most of devices use Chrome as WebView implementation by default. So you can give an advice to user to update Chrome (the latest version is 93). This is a problem of environment but not of the library

**Comment by timocov** [comment]
> '#2962ff4c'

How this color was generated? Even though [lightweight-charts seems support](https://github.com/tradingview/lightweight-charts/blob/e5133cb0c50fc557182aba4011e170aaf30a5b1a/src/helpers/color.ts#L218) `#rrggbbaa` notation, but according to https://caniuse.com/css-rrggbbaa this is not supported by Chrome < 62.

**Comment by makedonsky94** [comment]
We can fix the serialization of colors in the next update. I will add this issue in the milestone

**Comment by shahradelahi** [comment]
Dear @makedonsky94, your advice was useful. 

I updated Google Chrome to 93 (it was 61) and the problem has been solved.

But I have another question, what do I do with users who don't have Google Chrome by default Or the users who don't even have Chrome.

**Comment by shahradelahi** [comment]
@timocov I didn't find this code on my project and that's not from me because I just copied the sample codes!

**Comment by shahradelahi** [comment]
Thanks, your information helped me a lot.
