### ISSUE TITLE
Upgrade the lightweight-charts to 3.0

### ISSUE THREAD

**Issue by keyhuihk01** [tradingview/lightweight-charts-android#9]
The latest lightweight-charts library is v3.1.5.
As a new Android library, i see current SDK is using v2, some features are not available.

Is it possible to start with latest js version ?
Thanks.

**Comment by timocov** [comment]
@makedonsky94 can you please take a look

**Comment by makedonsky94** [comment]
Hi!
At the moment we are focusing on stability of the api. 
We are considering to migrate to the latest version of js library. 
I will inform you when the new version of Kotlin library will be available.
