### ISSUE TITLE
How to load history data in realtime when scroll from right to left

### ISSUE THREAD

**Issue by pankajlcx** [tradingview/lightweight-charts-android#92]

**Comment by timocov** [comment]
Please take a look at this example https://jsfiddle.net/TradingView/fg7yez2s/, I think you can do something like that but with the data at the right instead.

**Comment by pankajlcx** [comment]
hi @timocov i checked it, i want to implement the same with android sdk. Do we have any example how to call api in realtime and append the data in history during the scroll

**Comment by makedonsky94** [comment]
Android library has the same API as javascript library unlike of chart creating. So you can check examples in javascript and write almost the same code in Kotlin.

>Do we have any example how to call api in realtime

What do you mean? You can add the new data by using [update](https://github.com/tradingview/lightweight-charts/blob/master/docs/series-basics.md#update) method in series
