### ISSUE TITLE
lateinit property histogramSeries has not been initialized

### ISSUE THREAD

**Issue by Ali1067** [tradingview/lightweight-charts-android#95]
lateinit var histogramSeries: SeriesApi

charts_view.api.addHistogramSeries(
    onSeriesCreated = { series ->
        histogramSeries = series
    }
)

the issue is, histogramSeries = series never called. any solution?

**Comment by makedonsky94** [comment]
Hi! Can you make an example project with reproducing of this bug?

**Comment by Ali1067** [comment]
@makedonsky94  i just followed the instructions of their official git. (link attached). i'm building on android studio 2020.3.1 with kotlin. 

https://github.com/tradingview/lightweight-charts-android

**Comment by Ali1067** [comment]
![tradeview](https://user-images.githubusercontent.com/25032829/144386835-16238138-ed73-4aa9-a71c-553a5054c449.PNG)

**Comment by makedonsky94** [comment]
Can you check the version of WebView?

**Comment by makedonsky94** [comment]
The library supports WebView implementations with version above 51. You can check it [here](https://caniuse.com/?search=es6)

If you running the example in this repository on virtual device, there might be errors because of old implementations of WebView.

**Comment by Ali1067** [comment]
Using Chrome on Samsung Device which have Version 96.0.4664.45. (not working)
 tested on emulator pixel5 . faced the same issue. would appreciate if you can please help to figure out.

**Comment by makedonsky94** [comment]
I just realized that code in the screenshot is expecting that series could be created asynchronously. The method addSeries is  asynchronous and setting data should be placed in lambda `onSeriesCreated`

**Comment by Ali1067** [comment]
Resolved. Thanks for your help!
